### ISSUE TITLE
can we have some benchmarks camparison with other forth and the primary languages?

### ISSUE THREAD

**Issue by yunfan** [onatto/dotforth#2]
i am just shocked of gforth-fast can not beaten kotlin and java. so just curious if this dotforth could

**Comment by onatto** [comment]
I don't know what kind of optimizations gforth-fast does, but I think gforth would be faster since this implementation is just educational, nothing serious, providing bare minimum to build your own. I don't plan to build upon this, sorry.

One relatively simple optimization: You could write the ops as NASM macros and generate inlined code which will be faster than the interpreter at the cost of instruction cache pressure and executable size.

So, the assembly NASM ends up transforming looks like:
`fop_pushint 1`
`fop_pushint 2`
`fop_iadd`

**Comment by yunfan** [comment]
thanks for the tips.
